# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: anomaly.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'anomaly.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ranomaly.proto\x12\x07\x61nomaly\"l\n\x05\x46rame\x12\x12\n\nimage_jpeg\x18\x01 \x01(\x0c\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\x03\x12\x11\n\ttimestamp\x18\x03 \x01(\x01\x12\x0b\n\x03lat\x18\x04 \x01(\x01\x12\x0b\n\x03lon\x18\x05 \x01(\x01\x12\x10\n\x08want_vlm\x18\x06 \x01(\x08\"\x81\x01\n\tDetection\x12\r\n\x05label\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\n\n\x02x1\x18\x03 \x01(\x02\x12\n\n\x02y1\x18\x04 \x01(\x02\x12\n\n\x02x2\x18\x05 \x01(\x02\x12\n\n\x02y2\x18\x06 \x01(\x02\x12\x10\n\x08on_floor\x18\x07 \x01(\x08\x12\x14\n\x0croad_overlap\x18\x08 \x01(\x02\"\xec\x01\n\x0b\x46rameResult\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x03\x12&\n\ndetections\x18\x02 \x03(\x0b\x32\x12.anomaly.Detection\x12\x0f\n\x07vlm_ran\x18\x03 \x01(\x08\x12\x13\n\x0b\x66inal_label\x18\x04 \x01(\t\x12\x17\n\x0fpothole_present\x18\x05 \x01(\x08\x12\x13\n\x0bvlm_comment\x18\x06 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x07 \x01(\t\x12\x13\n\x0b\x64\x65tector_ms\x18\x08 \x01(\x01\x12\x0e\n\x06vlm_ms\x18\t \x01(\x01\x12\x0b\n\x03lat\x18\n \x01(\x01\x12\x0b\n\x03lon\x18\x0b \x01(\x01\x32|\n\x0e\x41nomalyService\x12\x39\n\rAnalyzeStream\x12\x0e.anomaly.Frame\x1a\x14.anomaly.FrameResult(\x01\x30\x01\x12/\n\x07\x41nalyze\x12\x0e.anomaly.Frame\x1a\x14.anomaly.FrameResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'anomaly_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAME']._serialized_start=26
  _globals['_FRAME']._serialized_end=134
  _globals['_DETECTION']._serialized_start=137
  _globals['_DETECTION']._serialized_end=266
  _globals['_FRAMERESULT']._serialized_start=269
  _globals['_FRAMERESULT']._serialized_end=505
  _globals['_ANOMALYSERVICE']._serialized_start=507
  _globals['_ANOMALYSERVICE']._serialized_end=631
# @@protoc_insertion_point(module_scope)
