// Generated by `supabase gen types` (via Supabase MCP) against project joixzhdpnxqhnuscxsoy.
//
// The browser's `authenticated` role has NO usage on the custom schemas
// (platform/vision/priority/geo/analysis) — verified 2026-06-20. All frontend
// reads therefore go through the `public.app_*` security-definer RPC layer
// (migrations 0200_app_read_api.sql + 0201_app_map_volume.sql), which is what
// these types describe.
// Regenerate after changing 0200/02xx: Supabase MCP `generate_typescript_types`.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      _app_tenant: { Args: never; Returns: string }
      app_active_tenant: {
        Args: never
        Returns: {
          accent: string
          tenant_id: string
          tenant_name: string
        }[]
      }
      app_authorize_object: {
        Args: { p_bucket: string; p_path: string }
        Returns: boolean
      }
      app_current_rois: {
        Args: { p_dimensions?: string[]; p_limit?: number }
        Returns: {
          centroid_lat: number
          centroid_lng: number
          description: string
          dominant_type: string
          geom_geojson: Json
          id: string
          risk_dimension: string
          risk_score: number
          signal_count: number
        }[]
      }
      app_roi_dimension_counts: {
        Args: never
        Returns: {
          max_risk: number
          risk_dimension: string
          roi_count: number
        }[]
      }
      app_get_run: { Args: { p_id: string }; Returns: Json }
      app_list_runs: {
        Args: never
        Returns: {
          budget: number
          created_at: string
          id: string
          is_latent: boolean
          kind: string
          status: string
        }[]
      }
      app_map_observations: {
        Args: never
        Returns: {
          district_cve: string
          district_name: string
          id: string
          lat: number
          lng: number
          slug: string
          source: string
          state: string
          sweep: string
          thumb_path: string
          volume: number
          weight: number
          zone: string
        }[]
      }
      app_observation_detail: {
        Args: { p_id: string }
        Returns: {
          conf: number
          confirmations: number
          detector: string
          district_name: string
          frame_ref: string
          id: string
          image_bbox: Json
          label: string
          lat: number
          lng: number
          misses: number
          observed_at: string
          qty: number
          recording_id: string
          slug: string
          state: string
          sweep: string
          unit: string
          weight: number
          zone: string
        }[]
      }
      app_observation_types_counts: {
        Args: never
        Returns: {
          category: string
          current_count: number
          is_latent: boolean
          label: string
          slug: string
        }[]
      }
      app_sweep_route: {
        Args: { p_observation_id: string }
        Returns: {
          area_km2: number
          coverage_geojson: Json
          ended_at: string
          obs_count: number
          origin_lat: number
          origin_lng: number
          started_at: string
          sweep: string
        }[]
      }
      app_tenant_boundary: { Args: never; Returns: Json }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
